import "./globals.css";
import { Metadata } from "next";

export const metadata : Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>My nav</h1>
        </nav>
        {children}    {/* 다른 페이지가 여기 들어감    */}
      </body>
    </html>
  );
}

// 모든 페이지에 표시
